//-----------------------------------------------------
// Project Name : a.out

//***Headers***
//***Module***
module fetch #(
        parameter integer AddrSize = 1
    )
    (
        input  clk_i ,
        input  rst_i ,
        input  pc_i ,
        output nextpc_o ,
        output [AddrSize - 1 : 0] instruction_o 
    );

//***Interal logic generated by compiler***  


//***Handcrafted Internal logic*** 
//TODO
endmodule
