def help():
    print("================================")
    print("Usage: python3 parser.py --input filename.txt --output filename.txt")
    print("--input        Specify the netlist used as input data for the Parser")
    print("--output       Specify the name of the output .ck file")
    print("--help | -h    Print this information")

def input_missing():
    print('ERROR: No inputFile specified. Use --help or -h for help on usage.')

def output_missing():
    print("Warning: No output file specified. Using default: autogenerated.ck")

def args_error():
    print("Incorrect usage, please, review the arguments.")
    print("Usage reminder: ")
    help()